version: '2'
services:    # Must be present exactly once at the beginning of the docker-compose.yml file
    cfsd19-logic-pathplanner:
        image: namv1994/cfsd-logic-pathplanner:v0.4
        network_mode: "host"
        ipc: host
        environment:
          - DISPLAY=$DISPLAY
        command: "cfsd-logic-pathplanner --cid=253 --debug --verbose --freq=30"
