version: '2'
services:    # Must be present exactly once at the beginning of the docker-compose.yml file
    cfsd19-logic-pathplanner:
        image: namv1994/cfsd-logic-pathplanner:v0.8
        network_mode: "host"
        ipc: host
        environment:
          - DISPLAY=$DISPLAY
        command: "cfsd-logic-pathplanner --cid=253 --verbose --m_guessDistance=5.0 --m_seperateDistance=1 --freq=30 --m_useGuessCones --m_useOneConeLine --m_numberPathPoints=12 --m_maxConeDistance=10 --m_useConesInFront"
    #--m_useCloseCones --m_useConesInFront --m_maxConeDistance --m_numberPathPoints --m_guessDistance --m_useGuessCones --m_useOneConeLine --m_seperateDistance
