version: '2'
services:    # Must be present exactly once at the beginning of the docker-compose.yml file
    cfsd19-cognition-detectconelane:
        image: chalmersfsd/cfsd-logic-pathplanner:v0.2
        network_mode: "host"
        ipc: host
        environment:
          - DISPLAY=$DISPLAY
        command: "cfsd-logic-pathplanner --cid=253"
