version: '2'
services:    # Must be present exactly once at the beginning of the docker-compose.yml file
    cfsd19-cognition-detectconelane:
        image: cfsd19-cognition-detectconelane:v0.2
        network_mode: "host"
        ipc: host
        environment:
          - DISPLAY=$DISPLAY
        command: "/usr/bin/cfsd19-cognition-detectconelane --cid=219  --verbose --freq=10"
